Привет,

Сегодня мы узнаем
* Как астрология может предсказать вашу склонность к той или иной науке
* [Поправка на множественные сравнения](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0_%D0%BD%D0%B0_%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%83%D1%8E_%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D1%83_%D0%B3%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%B7?oldformat=true)

In [1]:
import numpy as np

educations = ['cs', 'phys' ,'math','art','bio' ]
zodiacs= [
      'Aries'       ,'Taurus'    ,'Gemini'  , 'Cancer'  ,
      'Leo'         ,'Virgo'     ,'Libra'   , 'Scorpio' ,
      'Sagittarius' ,'Capricorn' ,'Aquarius', 'Pisces']
n_zod = len(zodiacs)
n_edu = len(educations)

print(f'Zodiac Signs    {n_zod}')
print(f'Faculies number {n_edu}')


Zodiac Signs    12
Faculies number 5


К сожалению, у меня сейчас нет возможности провести настоящий соцопрос, поэтому мы сделаем вот что.

Будем использовать случайные (ну ладно, псевдослучайные) значения.

Вот так мы можем сгенерировать строку целых чисел от 0 до 3 длиной 10

In [127]:
print(np.random.randint( 3+1 ,size = 10))

[0 2 1 2 3 0 3 3 3 3]


In [34]:
def generate_students(n_stud=10,n_zod = n_zod, n_edu = n_edu ):
    return np.hstack([np.vstack([np.full(n_stud,e),np.random.randint(n_zod ,size = n_stud)]) for e in range(n_edu)]).T

n_stud = 5;
students = generate_students(5);
print(students)

[[ 0 10]
 [ 0  1]
 [ 0 10]
 [ 0  0]
 [ 0  6]
 [ 1  5]
 [ 1  9]
 [ 1  9]
 [ 1  1]
 [ 1 10]
 [ 2  8]
 [ 2 11]
 [ 2  0]
 [ 2  2]
 [ 2  2]
 [ 3  5]
 [ 3  6]
 [ 3 10]
 [ 3  2]
 [ 3  5]
 [ 4  6]
 [ 4  4]
 [ 4  7]
 [ 4  0]
 [ 4  5]]


In [22]:
print('  ID   Faculty    Zodiac')
for i,s in enumerate(students[:]):
    print(f'#{i:2}    {educations[s[0]]:6} {zodiacs[s[1]]:10}')

  ID   Faculty    Zodiac
# 0    cs     Virgo     
# 1    cs     Cancer    
# 2    cs     Aries     
# 3    cs     Cancer    
# 4    cs     Sagittarius
# 5    phys   Pisces    
# 6    phys   Libra     
# 7    phys   Capricorn 
# 8    phys   Capricorn 
# 9    phys   Gemini    
#10    math   Taurus    
#11    math   Sagittarius
#12    math   Gemini    
#13    math   Taurus    
#14    math   Virgo     
#15    art    Sagittarius
#16    art    Virgo     
#17    art    Leo       
#18    art    Virgo     
#19    art    Libra     
#20    bio    Cancer    
#21    bio    Cancer    
#22    bio    Cancer    
#23    bio    Libra     
#24    bio    Leo       


Подсчитаем распределение. Создадим пустую таблицу distr, где ячейке с координатами I,J будет соответсвовать число студентов с зодиаком номер I и факультетом номер J

In [29]:
def calc_distr(students):
    distr = np.zeros([n_zod,n_edu])
    for s in students:
        I = s[1]
        J = s[0]
        distr[ I , J ]+= 1
    return distr
print(calc_distr(students))



[[1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 1. 1. 0. 0.]
 [2. 0. 0. 0. 3.]
 [0. 0. 0. 1. 1.]
 [1. 0. 1. 2. 0.]
 [0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


Хм, получились какие цифры. 

$E = N * \frac{1}{n_{edu}} * \frac{1}{/n_{zod}}$

In [33]:
expected =  n_stud  * 1/n_zod

print('Expected number of each combination %2.2f'%expected)
distr_norm = ((distr/expected)-1)*100

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(8,8))
ax = sns.heatmap(distr, linewidth=1.5,annot=True,xticklabels=educations,yticklabels=zodiacs)


plt.show()

print(np.sum(distr,axis=0)*1/n_zod)


NameError: name 'n_stud' is not defined